### ISSUE TITLE
Fix chat - photo sending in chat

### ISSUE THREAD

**Issue by gyroflaw** [fanse-work/fanse-backend#1]
fix error sending photo in chat

when user go to chat page and try to send photo, it send error text

https://fanse.co/messages

maybe hint = https://stackoverflow.com/questions/47128903/errors-this-action-is-unauthorized-using-form-request-validations-in-laravel

![Image](https://user-images.githubusercontent.com/83718263/192150596-fafe50af-8a72-4846-8058-482f445f067d.png)

**Comment by Mind1995Star** [comment]
If you give me 10-20 hours of time, I will fix it.

**Comment by jay0x5** [comment]
@Mind1995Star too long, max we can give you is 8hours
The issue is partially identified, all you have to do is find the source and fix it.

**Comment by Mind1995Star** [comment]
But @jay0x5 
Currently, I have other task, so I can't start development for this task right now.

**Comment by jay0x5** [comment]
@Mind1995Star no problem, we will check with you for some other task in some other time.
